"""Stage 4 — write screened PFs into a domain library.

Two deliberate constraints:

  * generated PFs land in `skills/<domain>/generated_pfs.py`, NEVER in the
    hand-written `evidence_pfs.py`. The hand-written library stays the thing a
    person owns and the thing every measured result was produced with.
  * the file is NOT loaded by default. `dynamic_program_functions.py`
    chain-loads `evidence_pfs.py` only; wiring generated PFs in is a separate,
    explicit `--register` step. Passing the screening gate earns a candidate an
    end-to-end run, not a place in a training rollout.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import List

from .spec import PFSpec, skill_md_frontmatter

_HASP = Path(__file__).resolve().parents[2]

_HEADER = '''"""PFs generated by forge — DO NOT EDIT BY HAND.

Each PF below passed the screening gate in `skills_construct/forge/screen.py`: it fires on a
real population of wrong solutions, stays near-silent on correct ones, and
separates the two sets by at least the calibrated lift. That earns it an
end-to-end regeneration run — it does NOT mean its effect on accuracy has been
measured. Only the numbers in the workspace README are measured.

Regenerate with:  python -m skills_construct.forge --stage emit --domain {domain} --tag {tag}
Screened on:      {corpus}
"""
from __future__ import annotations

import importlib.util as _iu
import re  # noqa: F401  (available to generated checkers)
from math import gcd  # noqa: F401
from pathlib import Path as _P
from typing import Optional  # noqa: F401


def _load_evidence_module():
    """Reuse the hand-written library's registration helper and step splitter."""
    p = _P(__file__).resolve().parent / "evidence_pfs.py"
    spec = _iu.spec_from_file_location("_hasp_evidence_pfs_for_generated", str(p))
    mod = _iu.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_EV = _load_evidence_module()
_family = _EV._family
'''

_SKILL_MD = """{frontmatter}

# {skill_id}

**Generated by forge** from {n_src} wrong cases in the `{family}` family.
Not hand-written; not yet measured end-to-end.

## Anchor
- **level**: {level} — {level_note}
- **trigger**: {trigger}
- **evidence**: {evidence}

## Scope
{scope}

## Why this is checkable
{rationale}

## Screening (offline, `skills_construct/forge/screen.py`)
| | fires on | |
|---|---|---|
| wrong solutions | {fw:.1%} | population |
| correct solutions | {fc:.1%} | false-positive floor |
| lift | {lift} | gate requires >= 2.0 |

Sample verdicts:
{samples}

## Status
Screened only. Run `anchor/eval_polished_pfs.py` to measure accuracy
before -> after before using this in training.
"""


def _render_pf(s: PFSpec) -> str:
    src = s.checker_src.strip()
    # namespace the entry point so several generated checkers can coexist
    src = src.replace("def check(", f"def _check_{s.skill_id}(", 1)
    kind_arg = "step_checker" if s.checker_kind == "step" else "answer_checker"
    anchor = json.dumps({"level": s.anchor.get("level", "step"),
                         "trigger": s.anchor.get("trigger", ""),
                         "evidence": s.anchor.get("evidence", "deterministic")})
    scope = s.family_scope.replace('"', "'")
    sc = s.screen or {}
    return (
        f"\n\n# ── {s.skill_id} "
        f"(screened: wrong {sc.get('fire_wrong', 0):.1%} / correct {sc.get('fire_correct', 0):.1%}, "
        f"lift {sc.get('lift', 0)}) ──\n"
        f"{src}\n\n"
        f'_family("{s.skill_id}",\n'
        f'        "{scope}",\n'
        f"        {kind_arg}=_check_{s.skill_id},\n"
        f"        can_repair={bool(s.can_repair)},\n"
        f"        anchor={anchor})\n"
    )


def emit(specs: List[PFSpec], domain: str, tag: str, corpus_desc: str,
         register: bool = False) -> Path:
    accepted = [s for s in specs if (s.screen or {}).get("verdict") == "accept"]
    # Generated PFs carry a checker, so they belong to the executable half —
    # the module next to evidence_pfs.py, its cards under executable/docs/.
    lib = _HASP / "skills" / "executable" / domain
    if not lib.is_dir():
        raise SystemExit(f"no such domain library: {lib}")
    cards = _HASP / "skills" / "executable" / "docs" / domain
    cards.mkdir(parents=True, exist_ok=True)

    out = lib / "generated_pfs.py"
    body = _HEADER.format(domain=domain, tag=tag, corpus=corpus_desc)
    for s in accepted:
        body += _render_pf(s)
    if not accepted:
        body += "\n\n# No candidate passed the screening gate.\n"
    out.write_text(body)

    for s in accepted:
        d = cards / s.skill_id
        d.mkdir(exist_ok=True)
        sc = s.screen or {}
        samples = "\n".join(
            f"- `{x['label']}` {x['verdict'][:160]}" for x in sc.get("samples", [])[:4]
        ) or "- (none recorded)"
        (d / "SKILL.md").write_text(_SKILL_MD.format(
            # mandatory: a SKILL.md without frontmatter is rejected by
            # MarkdownSkillLoader, leaving the PF registered but unselectable
            frontmatter=skill_md_frontmatter(s),
            skill_id=s.skill_id, n_src=len(s.source_uids), family=tag,
            level=s.anchor.get("level", ""),
            level_note=("a specific reasoning step, reported as @step k/N"
                        if s.anchor.get("level") == "step" else "the committed answer"),
            trigger=s.anchor.get("trigger", ""), evidence=s.anchor.get("evidence", ""),
            scope=s.family_scope, rationale=s.rationale or "(not stated)",
            fw=sc.get("fire_wrong", 0.0), fc=sc.get("fire_correct", 0.0),
            lift=sc.get("lift", 0.0), samples=samples))

    if register:
        _wire_in(lib)
    return out


def _wire_in(lib: Path) -> None:
    """Explicit opt-in: chain-load generated_pfs.py after evidence_pfs.py.

    The chain-load is appended to `evidence_pfs.py`, which is itself chain-loaded
    by the textual half's `dynamic_program_functions.py` — so a generated PF
    registers last and overrides anything with the same id.
    """
    dpf = lib / "evidence_pfs.py"
    txt = dpf.read_text()
    if "_load_generated_pfs" in txt:
        return
    txt += textwrap.dedent('''

        # ── forge: generated PFs (opt-in, added by `forge --stage emit --register`) ──
        def _load_generated_pfs():
            import importlib.util as _iu
            from pathlib import Path as _P
            p = _P(__file__).resolve().parent / "generated_pfs.py"
            if p.exists():
                spec = _iu.spec_from_file_location("_hasp_generated_pfs", str(p))
                mod = _iu.module_from_spec(spec)
                spec.loader.exec_module(mod)


        _load_generated_pfs()
        ''')
    dpf.write_text(txt)
